# Generated by Django 5.0.2 on 2024-02-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_banner_created_at_alter_category_created_at_and_more'),
        ('product', '0003_remove_warrantytype_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantytype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.group'),
        ),
        migrations.AddField(
            model_name='warrantytype',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subcategory'),
            preserve_default=False,
        ),
    ]
