# Generated by Django 5.0.2 on 2024-02-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_warrantytype_group_warrantytype_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beauty_glamour',
            field=models.BooleanField(default=False, null=True, verbose_name='Beauty & Glamour'),
        ),
        migrations.AddField(
            model_name='product',
            name='best_price_guaranteed',
            field=models.BooleanField(default=False, null=True, verbose_name='Best Price Guaranteed'),
        ),
        migrations.AddField(
            model_name='product',
            name='everyday_low_price',
            field=models.BooleanField(default=False, null=True, verbose_name='Everyday Low Price!'),
        ),
        migrations.AddField(
            model_name='product',
            name='fashion',
            field=models.BooleanField(default=False, null=True, verbose_name='Fashion'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False, null=True, verbose_name='Free Delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='home_makeover',
            field=models.BooleanField(default=False, null=True, verbose_name='Home Makeover'),
        ),
        migrations.AddField(
            model_name='product',
            name='mart',
            field=models.BooleanField(default=False, null=True, verbose_name='Mart'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.BooleanField(default=False, null=True, verbose_name='Wholesale Price'),
        ),
    ]
