# Generated by Django 5.0.2 on 2024-02-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_colorfamily_category_colorfamily_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='colorfamily',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'ColorFamily'},
        ),
        migrations.AlterModelOptions(
            name='listedyearseason',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Listed Year Season'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Country Name'},
        ),
        migrations.AlterModelOptions(
            name='mainmaterial',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Main Material'},
        ),
        migrations.AlterModelOptions(
            name='menstrend',
            options={'ordering': ['-created_at'], 'verbose_name_plural': "Men's Trend"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Size'},
        ),
        migrations.AlterModelOptions(
            name='sizename',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'SizeName'},
        ),
        migrations.AlterModelOptions(
            name='warrantyperiod',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Warranty Period'},
        ),
        migrations.AlterModelOptions(
            name='warrantytype',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Warranty Type'},
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='colorfamily',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='listedyearseason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menstrend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sizename',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantyperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
