# Generated by Django 5.0.2 on 2024-02-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
