# Generated by Django 5.0.2 on 2024-02-20 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_content_conversationmessage_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='members',
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
