# Generated by Django 5.0.2 on 2024-02-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_rename_product_conversation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='receiver',
            new_name='receiever',
        ),
    ]
