# Generated by Django 5.0.2 on 2024-02-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_rename_receiver_conversation_receiever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='receiever',
            new_name='reciever',
        ),
    ]
